### ISSUE TITLE
update: use `os.ReadDir` instead of `ioutil.ReadDir`

### ISSUE THREAD

**Issue by raklaptudirm** [shoumodip/fm#1]
Using `ioutil` package in go code is considered bad practice since go 1.16. Equivalent functions provided by `os` package should be used instead.

From the `ioutil` docs:
> As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.

From `ioutil.ReadDir` docs:
> As of Go 1.16, os.ReadDir is a more efficient and correct choice: it returns a list of fs.DirEntry instead of fs.FileInfo, and it returns partial results in the case of an error midway through reading a directory.

**Comment by shoumodip** [comment]
Fixed in a4c6d7d

Thanks for your participation! :+1:
